name: distrib_agnostic_graph_tr
channels:
  - conda-forge
  - dglteam
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.6
  - dgl-cuda11.6=0.9.1
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu116
      - contextily==1.4.0
      - fiona==1.9.5
      - geopandas==0.14.1
      - ipykernel==6.27.1
      - jupyter==1.1
      - libpysal==4.9.2
      - mapclassify==2.6.1
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - networkx==3.1
      - pandas==2.1.4
      - pydantic==2.9.2
      - pyyaml==6.0.1
      - rasterio==1.3.9
      - scikit-learn==1.3.2
      - seaborn==0.13.0
      - tensorboardx==2.6.2.2
      - torch==1.13.1
      - tornado==6.4
      - tqdm==4.65.0

